<?php

function greeting_menu() {
  $items = array();
  $items['hello_friend'] = array(
    'title' => 'Hey Bro',
    'page callback' => 'say_hello',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['later'] = array(
    'title' => 'later bro',
    'page callback' => 'say_later',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,

  );

  $items['clear_cache'] = [
    'title' => '$: drush cc all',
    'page callback' => 'clear_cache',
    // 'page arguements' => array(1),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  ];
  return $items;
}
function greeting_init(){

  $_SESSION['last_page']= $_GET['q'];
  // var_dump($_SESSION['last_page']);
  $last_path = $_SESSION['last_page'];
  var_dump($_SESSION['last_page']);
  var_dump(''.$last_path.'');
}

function clear_cache(){
  // shell_exec("drush cc all");
  // $_GET['destination'] = 'hello_friend';
  $last_path = $_SESSION['last_page'];
  drupal_flush_all_caches();
  var_dump(''.$last_path.'');
  // drupal_goto(''.$last_path.'');
  return "<script>window.history.back();</script>";
}

function say_hello() {
  return '<p>Hello my dear bro!</p>';
}

function say_later() {

  return '<h3>Later Brosephine</h3>';
}

function greeting_user_login()
{
  $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout ()
{
  $_GET['destination'] = 'later';
}
